//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_taller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public long Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
        public long IdCliente { get; set; }
        public long IdTaller { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Taller Taller { get; set; }
    }
}
